Imports

In [4]:
import numpy as np

Question 1:
For the matrix A Find a vector x that maximizes
\begin{gather*}
    A = \left[\begin{array}{cccc}
    1 & 2 & 3 & 4\\
    2 & 4 & -4 & 8\\
    -5 & 4 & 1 & 5\\
    5 & 0 & -3 & -7
    \end{array}\right]
\end{gather*}




1A:
\begin{gather*}
    \left\Vert A\right\Vert _{1}= max_{x}\frac{\left\Vert Ax\right\Vert _{1}}{\left\Vert x\right\Vert _{1}} = max_{j}(\mathop{\sum_{i=1}^{m}|a_{ij}|})
\end{gather*}

In [5]:
x = [0,0,0,1]
x

[0, 0, 0, 1]

Question 1a:
 
Find a vector x that maximizes 
\begin{gather*}
    \left\Vert A\right\Vert _{\infty}= max_{x}\frac{\left\Vert Ax\right\Vert _{\infty}}{\left\Vert x\right\Vert _{\infty}} = max_{i}(\mathop{\sum_{j=1}^{n}|a_{ij}|})
\end{gather*}

In [6]:
x = [1,1,-1,1]
x

[1, 1, -1, 1]

Question 1b:
 
Find a vector x that maximizes 
\begin{gather*}
    \left\Vert A\right\Vert _{2}= max_{x}\frac{\left\Vert Ax\right\Vert _{2}}{\left\Vert x\right\Vert _{2}} = \sigma_{max}
\end{gather*}

In [7]:
A = np.array([[1, 2, 3, 4],
                  [2, 4, -4, 8],
                  [-5, 4, 1, 5],
                  [5, 0, -3, -7]])
U, sigma, V_T = np.linalg.svd(A)
print(np.max(sigma))
e_vector = V_T[np.argmax(sigma)]
print(e_vector)
x = np.linalg.norm(A @ e_vector)
print(x)

13.858100376465329
[-0.29618621  0.35616716  0.06730298  0.88367923]
13.858100376465327


Question 4: Least Squares

4A: Upper triangular linear systems

In [8]:
def BwdSub(U, b):
    n = len(b)
    x = np.zeros(n)
    for i in reversed(range(0, n)):
        b_temp = b[i]
        for j in reversed(range(i, n)):
            b_temp -= U[i][j] * x[j]
        x[i] = b_temp / U[i][i]
    print(f"BwdSub: {x}")
    return x

4A: Lower triangular linear systems

In [9]:
def FwdSub(L, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(0, n):
        b_temp = b[i]
        for j in range(0, i):
            b_temp -= L[i][j] * x[j]
        x[i] = b_temp / L[i][i]
    print(f"FwdSub: {x}")
    return x


4B:

Find the best approximation in a least square sense for satisfying the linear system
Ax = b where
\begin{gather*}
    A = \left[\begin{array}{ccc}
    2 & 1 & 2\\
    1 & -2 & 1\\
    1 & 2 & 3\\
    1 & 1 & 1
    \end{array}\right] , b = \left[\begin{array}{c}
    6\\
    1\\
    5\\
    2
    \end{array}\right]
\end{gather*}

In [27]:
A = np.array([[2, 1, 2],
                  [1, -2, 1],
                  [1, 2, 3],
                  [1, 1, 1]])
b = np.array([6, 1, 5, 2])

L = np.linalg.cholesky(A.T @ A)
y = FwdSub(L, A.T @ b)
x_4a = BwdSub(L.T, y)
print(f"x_opt: {x_4a}")

FwdSub: [7.55928946 2.51645638 1.06046696]
BwdSub: [1.7 0.6 0.7]
x_opt: [1.7 0.6 0.7]


4C: QR factorization

In [30]:
A = np.array([[2, 1, 2],
              [1, -2, 1],
              [1, 2, 3],
              [1, 1, 1]])
b = np.array([6, 1, 5, 2])
Q, R = np.linalg.qr(A)
v = Q.T @ b
x_qr = BwdSub(R, v)
print(f"x_opt: {x_qr}")

BwdSub: [1.7 0.6 0.7]
x_opt: [1.7 0.6 0.7]


4C: SVD factorization

In [31]:
A = np.array([[2, 1, 2],
              [1, -2, 1],
              [1, 2, 3],
              [1, 1, 1]])
b = np.array([6, 1, 5, 2])
U, sigma, V_T = np.linalg.svd(A, full_matrices=False)
y = BwdSub(np.diag(sigma), U.T @ b)
x_svd = V_T.T @ y
print(f"x_opt: {x_svd}")

BwdSub: [-1.59353004  0.38516653 -1.02582101]
x_opt: [1.7 0.6 0.7]


4D: Compute the residual of the least squares system r = Ax − b,

In [34]:
r = A @ x_svd - b
r

array([-6.00000000e-01,  2.00000000e-01,  1.77635684e-15,  1.00000000e+00])

4E:

In [24]:
A = np.array([[2, 1, 2],
                  [1, -2, 1],
                  [1, 2, 3],
                  [1, 1, 1]])
b = np.array([6, 1, 5, 2])
i = 1
W = np.diag([1, 1, 1, 1])
x_est = np.linalg.inv(A.T @ W @ A) @ A.T @ W @ b
r = A @ x_est - b
print(f"r: {r}")
while np.abs(r[0]) >= 10 ** (-3):
    i += 1
    W = np.diag([i, 1, 1, 1])
    x_est = np.linalg.inv(A.T @ W @ A) @ A.T @ W @ b
    r = A @ x_est - b
print(f"W: {W}")
print(f"x_est: {x_est}")
print(f"Weights array: [{i},1,1,1]")

r: [-6.00000000e-01  2.00000000e-01  1.77635684e-15  1.00000000e+00]
W: [[808   0   0   0]
 [  0   1   0   0]
 [  0   0   1   0]
 [  0   0   0   1]]
x_est: [2.1722891  0.69215397 0.48113432]
Weights array: [808,1,1,1]


5. QR factorization

5.A Gram Schmidt

In [11]:
'''
Description: The algorithem get a matrix A and retuen the QR Facrotization using Gram Schmidt Algorithem
'''
def GramSchmidtQR(A):
    m , n  = A.shape
    R      = np.zeros((n,n))
    Q      = np.zeros((m,n))
    R[0,0] = np.linalg.norm(A[:,0])
    Q[:,0] = A[:,0] / R[0,0]
    for i in range(1,n):
        Q[:,i] = A[:,i]
        for j in range(i):
            R[j,i] = Q[:,j].transpose() @ A[:,i]
            Q[:,i] = Q[:,i] - R[j,i]*Q[:,j]
        R[i,i] = np.linalg.norm(Q[:,i])
        Q[:,i] = Q[:,i] / R[i,i]
        
    return Q,R


5.A: Modified Gram Schmidt

In [12]:
'''
Description: The algorithm recieves a matrix A and returns the QR Facrotization using modified Gram Schmidt Algorithem
'''
def ModifiedGramSchmidtQR(A):
    m , n  = A.shape
    R      = np.zeros((n,n))
    Q      = np.zeros((m,n))
    R[0,0] = np.linalg.norm(A[:,0])
    Q[:,0] = A[:,0] / R[0,0]
    for i in range(1,n):
        Q[:,i] = A[:,i]
        for j in range(i):
            R[j,i] = Q[:,j].transpose() @ Q[:,i]
            Q[:,i] = Q[:,i] - R[j,i]*Q[:,j]
        R[i,i] = np.linalg.norm(Q[:,i])
        Q[:,i] = Q[:,i] / R[i,i]
        
    return Q,R

5.B: find the QR factorization of the matrix
\begin{gather*}
    A = \left[\begin{array}{ccc}
    1 & 1 & 1\\
    \epsilon & 0 & 0\\
    0 & \epsilon & 0\\
    0 & 0 & \epsilon
    \end{array}\right] 
\end{gather*}

\begin{gather*}
    for : \epsilon = 1, \epsilon =1e-10
\end{gather*}

In [13]:
'''
Description: The procedure returns the matrix A with the asked epsilon
'''
def createAMAtrix(epsilon):
    return np.array([[1,1,1],[epsilon,0,0],[0,epsilon,0],[0,0,epsilon]])

def QrToString(epsilon):
    A   = createAMAtrix(epsilon)
    Q,R = GramSchmidtQR(A)
    print("Q:\n",Q,"\nR:\n",R)
    print("\nModified")
    Q, r = ModifiedGramSchmidtQR(A)
    print("Q:\n",Q,"\nR:\n",R)


\begin{gather*}
    for : \epsilon = 1
\end{gather*}

In [14]:
QrToString(1)

Q:
 [[ 0.70710678  0.40824829  0.28867513]
 [ 0.70710678 -0.40824829 -0.28867513]
 [ 0.          0.81649658 -0.28867513]
 [ 0.          0.          0.8660254 ]] 
R:
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]

Modified
Q:
 [[ 0.70710678  0.40824829  0.28867513]
 [ 0.70710678 -0.40824829 -0.28867513]
 [ 0.          0.81649658 -0.28867513]
 [ 0.          0.          0.8660254 ]] 
R:
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]


\begin{gather*}
    for : \epsilon =1e-10
\end{gather*}

In [15]:
QrToString(1e-10)

Q:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e-10 -7.07106781e-01 -7.07106781e-01]
 [ 0.00000000e+00  7.07106781e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.07106781e-01]] 
R:
 [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.41421356e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.41421356e-10]]

Modified
Q:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e-10 -7.07106781e-01 -4.08248290e-01]
 [ 0.00000000e+00  7.07106781e-01 -4.08248290e-01]
 [ 0.00000000e+00  0.00000000e+00  8.16496581e-01]] 
R:
 [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.41421356e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.41421356e-10]]


5.C For all factorizations, calculate
\begin{gather*}
    \left\Vert Q^{T}Q-I\right\Vert _{F}
\end{gather*}


In [16]:
def ForNormToString(epsilon):
    A   = createAMAtrix(epsilon)
    Q,R = GramSchmidtQR(A)
    forbinus_norm = np.linalg.norm(Q.T @ Q - np.eye(Q.shape[1]),'fro')
    print("\n||Q^TQ - I || F = " ,forbinus_norm)
    print("\nModified")
    Q, r = ModifiedGramSchmidtQR(A)
    forbinus_norm = np.linalg.norm(Q.T @ Q - np.eye(Q.shape[1]),'fro')
    print("\n||Q^TQ - I || F = " ,forbinus_norm)

\begin{gather*}
    for : \epsilon = 1
\end{gather*}

In [17]:
ForNormToString(1)


||Q^TQ - I || F =  5.319287782567757e-16

Modified

||Q^TQ - I || F =  4.987305196443834e-16


\begin{gather*}
    for : \epsilon = 1e-10
\end{gather*}

In [18]:
ForNormToString(1e-10)


||Q^TQ - I || F =  0.7071067811865477

Modified

||Q^TQ - I || F =  1.1547005383855976e-10
