Imports

In [1]:
import numpy as np

Question 1:
For the matrix A Find a vector x that maximizes
\begin{gather*}
    A = \left[\begin{array}{cccc}
    1 & 2 & 3 & 4\\
    2 & 4 & -4 & 8\\
    -5 & 4 & 1 & 5\\
    5 & 0 & -3 & -7
    \end{array}\right]
\end{gather*}




1A:
\begin{gather*}
    \left\Vert A\right\Vert _{1}= max_{x}\frac{\left\Vert Ax\right\Vert _{1}}{\left\Vert x\right\Vert _{1}} = max_{j}(\mathop{\sum_{i=1}^{m}|a_{ij}|})
\end{gather*}

hello 


Question 1a:
 
Find a vector x that maximizes 
\begin{gather*}
    \left\Vert A\right\Vert _{\infty}= max_{x}\frac{\left\Vert Ax\right\Vert _{\infty}}{\left\Vert x\right\Vert _{\infty}} = max_{i}(\mathop{\sum_{j=1}^{n}|a_{ij}|})
\end{gather*}

hello 


Question 1b:
 
Find a vector x that maximizes 
\begin{gather*}
    \left\Vert A\right\Vert _{2}= max_{x}\frac{\left\Vert Ax\right\Vert _{2}}{\left\Vert x\right\Vert _{2}} = \sigma_{max}
\end{gather*}

hello 


Question 4: Least Squares

4A: Upper triangular linear systems

hello 


4A: Lower triangular linear systems

hello 


4B:

Find the best approximation in a least square sense for satisfying the linear system
Ax = b where
\begin{gather*}
    A = \left[\begin{array}{ccc}
    2 & 1 & 2\\
    1 & -2 & 1\\
    1 & 2 & 3\\
    1 & 1 & 1
    \end{array}\right] , b = \left[\begin{array}{c}
    6\\
    1\\
    5\\
    2
    \end{array}\right]
\end{gather*}

hello 


4C: QR factorization

hello 


4C: SVD factorization

hello 


4D: Compute the residual of the least squares system r = Ax − b,

hello 


4E:

hello 


5. QR factorization

5.A Gram Schmidt

In [28]:
'''
Description: The algorithem get a matrix A and retuen the QR Facrotization using Gram Schmidt Algorithem
'''
def GramSchmidtQR(A):
    m , n  = A.shape
    R      = np.zeros((n,n))
    Q      = np.zeros((m,n))
    R[0,0] = np.linalg.norm(A[:,0])
    Q[:,0] = A[:,0] / R[0,0]
    for i in range(1,n):
        Q[:,i] = A[:,i]
        for j in range(i):
            R[j,i] = Q[:,j].transpose() @ A[:,i]
            Q[:,i] = Q[:,i] - R[j,i]*Q[:,j]
        R[i,i] = np.linalg.norm(Q[:,i])
        Q[:,i] = Q[:,i] / R[i,i]
        
    return Q,R


5.A: Modified Gram Schmidt

In [29]:
'''
Description: The algorithem get a matrix A and retuen the QR Facrotization using modified Gram Schmidt Algorithem
'''
def ModifiedGramSchmidtQR(A):
    m , n  = A.shape
    R      = np.zeros((n,n))
    Q      = np.zeros((m,n))
    R[0,0] = np.linalg.norm(A[:,0])
    Q[:,0] = A[:,0] / R[0,0]
    for i in range(1,n):
        Q[:,i] = A[:,i]
        for j in range(i):
            R[j,i] = Q[:,j].transpose() @ Q[:,i]
            Q[:,i] = Q[:,i] - R[j,i]*Q[:,j]
        R[i,i] = np.linalg.norm(Q[:,i])
        Q[:,i] = Q[:,i] / R[i,i]
        
    return Q,R

5.B: find the QR factorization of the matrix
\begin{gather*}
    A = \left[\begin{array}{ccc}
    1 & 1 & 1\\
    \epsilon & 0 & 0\\
    0 & \epsilon & 0\\
    0 & 0 & \epsilon
    \end{array}\right] 
\end{gather*}

\begin{gather*}
    for : \epsilon = 1, \epsilon =1e-10
\end{gather*}

In [41]:
'''
Description: The procedure return the matrix A with the asked epsilon
'''
def createAMAtrix(epsilon):
    return np.array([[1,1,1],[epsilon,0,0],[0,epsilon,0],[0,0,epsilon]])

def QrToString(epsilon):
    A   = createAMAtrix(epsilon)
    Q,R = GramSchmidtQR(A)
    print("Q\n",Q,"\nR\n",R)
    print("\nModified")
    Q, r = ModifiedGramSchmidtQR(A)
    print("Q\n",Q,"\nR\n",R)


\begin{gather*}
    for : \epsilon = 1
\end{gather*}

In [42]:
QrToString(1)

Q
 [[ 0.70710678  0.40824829  0.28867513]
 [ 0.70710678 -0.40824829 -0.28867513]
 [ 0.          0.81649658 -0.28867513]
 [ 0.          0.          0.8660254 ]] 
R
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]

Modified
Q
 [[ 0.70710678  0.40824829  0.28867513]
 [ 0.70710678 -0.40824829 -0.28867513]
 [ 0.          0.81649658 -0.28867513]
 [ 0.          0.          0.8660254 ]] 
R
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]


\begin{gather*}
    for : \epsilon =1e-10
\end{gather*}

In [43]:
QrToString(1e-10)

Q
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e-10 -7.07106781e-01 -7.07106781e-01]
 [ 0.00000000e+00  7.07106781e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.07106781e-01]] 
R
 [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.41421356e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.41421356e-10]]

Modified
Q
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e-10 -7.07106781e-01 -4.08248290e-01]
 [ 0.00000000e+00  7.07106781e-01 -4.08248290e-01]
 [ 0.00000000e+00  0.00000000e+00  8.16496581e-01]] 
R
 [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.41421356e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.41421356e-10]]


5.C For all factorizations, calculate
\begin{gather*}
    \left\Vert Q^{T}Q-I\right\Vert _{F}
\end{gather*}


In [44]:
def ForNormToString(epsilon):
    A   = createAMAtrix(epsilon)
    Q,R = GramSchmidtQR(A)
    forbinus_norm = np.linalg.norm(Q.T @ Q - np.eye(Q.shape[1]),'fro')
    print("\n||Q^TQ - I || F = " ,forbinus_norm)
    print("\nModified")
    Q, r = ModifiedGramSchmidtQR(A)
    forbinus_norm = np.linalg.norm(Q.T @ Q - np.eye(Q.shape[1]),'fro')
    print("\n||Q^TQ - I || F = " ,forbinus_norm)

\begin{gather*}
    for : \epsilon = 1
\end{gather*}

In [45]:
ForNormToString(1)


||Q^TQ - I || F =  5.319287782567757e-16

Modified

||Q^TQ - I || F =  4.987305196443834e-16


\begin{gather*}
    for : \epsilon = 1e-10
\end{gather*}

In [46]:
ForNormToString(1e-10)


||Q^TQ - I || F =  0.7071067811865477

Modified

||Q^TQ - I || F =  1.1547005383855976e-10
